version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ror-reconciler:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3100:3100"
    networks:
      - rornet
networks:
  rornet:
