version: "3"

services:
  web:
    env_file: .env
    build: .
    image: rorcommunity/ror-reconciler
    ports:
      - "9292:80"
      - "2222:22"
    volumes:
      - ./spec:/home/app/webapp/spec
      - ./app.rb:/home/app/webapp/app.rb
